package com.blog.model;

import java.util.List;

import com.blog.model.base.BaseCategory;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Category extends BaseCategory<Category> {
	public static final Category dao = new Category();
	
	/**
	 * 根据类名查询该类的数量
	 * @param name
	 * @return
	 */
	public static int getNumberByName(String name) {
		List<Category> categoryList = Category.dao.find("select * from category where name = ?", name);
		return categoryList.size();
	}
	
	/**
	 * 查询类别并分页
	 * @param pageNumber
	 * @param pageSize
	 * @return
	 */
	public static Page<Record> paginate(int pageNumber, int pageSize) {
		String select = "select * ";
		String sqlExceptSelect = "from category Order By cdate desc";
		Page<Record> categoryPage = Db.paginate(pageNumber, pageSize, select, sqlExceptSelect);
		return categoryPage;
	}
	
	/**
	 * 查询类别总数
	 * @return
	 */
	public static int pageNumber() {
		String sql = "select * from category";
		List<Record> categoryList = Db.find(sql);
		return categoryList.size();
	}
}
