package com.blog.model;

import com.blog.model.base.BaseTags;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tags extends BaseTags<Tags> {
	public static final Tags dao = new Tags();

	/*
	 * 根据分页查询标签信息
	 */
	public static Page<Record> paginate(int pageNumber, int pageSize) {
		String select = "select * ";
		String sqlExceptSelect = "from tags";
		Page<Record> tagsPage = Db.paginate(pageNumber, pageSize, select, sqlExceptSelect);
		return tagsPage;
	}
}
