package com.blog.model;

import java.util.List;

import com.blog.model.base.BaseTags;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tags extends BaseTags<Tags> {
	public static final Tags dao = new Tags();

	/**
	 * 查询标签并分页
	 * @param pageNumber
	 * @param pageSize
	 * @return
	 */
	public static Page<Record> paginate(int pageNumber, int pageSize) {
		String select = "select * ";
		String sqlExceptSelect = "from tags Order By cdate desc";
		Page<Record> tagsPage = Db.paginate(pageNumber, pageSize, select, sqlExceptSelect);
		return tagsPage;
	}

	/**
	 * 查询标签总数
	 * @return
	 */
	public static int pageNumber() {
		String sql = "select * from tags";
		List<Record> tagsList = Db.find(sql);
		return tagsList.size();
	}

	/**
	 * 根据标签id删除标签
	 * @param id
	 * @return
	 */
	public static Boolean delTag(String id) {
		Db.update("delete from tags where id = ?", id);
		Boolean bool = Tags.dao.deleteById(id);
		return bool;
	}
	
	/**
	 * 根据标签名查询该标签的数量
	 * @param name
	 * @return
	 */
	public static int getNumberByName(String name) {
		List<Tags> tagsList = Tags.dao.find("select * from tags where name = ?", name);
		return tagsList.size();
	}
	
	/**
	 * 返回所有标签
	 * @return
	 */
	public static List<Tags> getAllTage() {
		List<Tags> tagList = Tags.dao.find("select * from tags");
		return tagList == null ? null : tagList;
	}
}
