package com.blog.model;

import java.util.List;

import com.blog.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
	
	/**
	 * 所有 sql 写在 Model 或 Service 中，不要写在 Controller 中
	 */
	public List<User> validateUserInfo(String username,String password){
		return find("select * from user where username="+username+"and password="+password);
	}
	
	public static User findUserByName(String username){
		return dao.findFirst("select * from user where username = ? limit 1",username);
	}
}
