package com.blog.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBlogTag<M extends BaseBlogTag<M>> extends Model<M> implements IBean {

	public void setBlogId(java.lang.String blogId) {
		set("blogId", blogId);
	}

	public java.lang.String getBlogId() {
		return get("blogId");
	}

	public void setTagId(java.lang.String tagId) {
		set("tagId", tagId);
	}

	public java.lang.String getTagId() {
		return get("tagId");
	}

	public void setComment(java.lang.String comment) {
		set("comment", comment);
	}

	public java.lang.String getComment() {
		return get("comment");
	}

}
