package com.blog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBlog<M extends BaseBlog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setAuthor(java.lang.String author) {
		set("author", author);
	}

	public java.lang.String getAuthor() {
		return get("author");
	}

	public void setSummary(java.lang.String summary) {
		set("summary", summary);
	}

	public java.lang.String getSummary() {
		return get("summary");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setUpVoteNum(java.lang.Integer upVoteNum) {
		set("upVoteNum", upVoteNum);
	}

	public java.lang.Integer getUpVoteNum() {
		return get("upVoteNum");
	}

	public void setReadNum(java.lang.Integer readNum) {
		set("readNum", readNum);
	}

	public java.lang.Integer getReadNum() {
		return get("readNum");
	}

	public void setPublishTime(java.util.Date publishTime) {
		set("publishTime", publishTime);
	}

	public java.util.Date getPublishTime() {
		return get("publishTime");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setCategoryId(java.lang.Integer categoryId) {
		set("categoryId", categoryId);
	}

	public java.lang.Integer getCategoryId() {
		return get("categoryId");
	}

	public void setLastUpdateTime(java.util.Date lastUpdateTime) {
		set("lastUpdateTime", lastUpdateTime);
	}

	public java.util.Date getLastUpdateTime() {
		return get("lastUpdateTime");
	}

	public void setCoverpicUrl(java.lang.String coverpicUrl) {
		set("coverPic_Url", coverpicUrl);
	}

	public java.lang.String getCoverpicUrl() {
		return get("coverPic_Url");
	}

	public void setTypeId(java.lang.String typeId) {
		set("typeId", typeId);
	}

	public java.lang.String getTypeId() {
		return get("typeId");
	}

	public void setStatusId(java.lang.String statusId) {
		set("statusId", statusId);
	}

	public java.lang.String getStatusId() {
		return get("statusId");
	}

}
